# gradle/libs.versions.toml
[versions]
agp = "8.1.0"
kotlin = "1.8.21"

appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
lifecycle = "2.6.1"
navigation = "2.6.0"
legacy = "1.0.0"
junit = "4.13.2"
ext_junit = "1.1.5"
espresso = "3.5.1"
retrofit = "2.9.0"
gson = "2.10.1"
scalars = "2.9.0"
desugar = "2.0.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "scalars" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

core-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
junit = { module = "junit:junit", version.ref = "junit" }

lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }

legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "ext_junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
